[package]
name = "stepper_servo_lib"
version = "0.1.0"
authors = ["SupaGait <gklomphaar@hotmail.com>"]
edition = "2018"

[dependencies]

[dependencies.num-traits]
version = "0.2.11"
default-features = false